import type { LucideIcon } from "lucide-react";
import {
  ShieldCheck,
  BadgeCheck,
  QrCode,
  Cloud,
  Printer,
  FileText,
  ClipboardCheck,
  Clock,
  CircleCheck,
  Search,
  Smartphone,
  Monitor,
  Database,
  Zap,
  Award,
  Star,
  Bell,
  Mail,
  Phone,
  MapPin,
  Package,
  Wrench,
  Users,
  Lock,
  Send,
  Layers,
  Truck,
  Gift,
  ThumbsUp,
  Sparkles,
  Headphones,
  CreditCard,
  Calendar,
  Tag,
  Building2,
  Rocket,
  Timer,
} from "lucide-react";

// Bộ icon để admin chọn cho từng dòng lợi ích ở panel đăng ký.
export const BENEFIT_ICON_MAP: Record<string, LucideIcon> = {
  ShieldCheck,
  BadgeCheck,
  QrCode,
  Cloud,
  Printer,
  FileText,
  ClipboardCheck,
  Clock,
  CircleCheck,
  Search,
  Smartphone,
  Monitor,
  Database,
  Zap,
  Award,
  Star,
  Bell,
  Mail,
  Phone,
  MapPin,
  Package,
  Wrench,
  Users,
  Lock,
  Send,
  Layers,
  Truck,
  Gift,
  ThumbsUp,
  Sparkles,
  Headphones,
  CreditCard,
  Calendar,
  Tag,
  Building2,
  Rocket,
  Timer,
};

export const BENEFIT_ICON_NAMES = Object.keys(BENEFIT_ICON_MAP);
export const DEFAULT_BENEFIT_ICON = "ShieldCheck";

export function benefitIcon(name: string): LucideIcon {
  return BENEFIT_ICON_MAP[name] || BENEFIT_ICON_MAP[DEFAULT_BENEFIT_ICON];
}
