-- Active: Supabase SQL Editor
-- Migration 004: Người dùng & phân vai trò (guest / manager / admin).
-- App vẫn đăng nhập được trước khi chạy migration (fallback ADMIN_PASSWORD -> admin).

CREATE TABLE IF NOT EXISTS pbh_users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    text UNIQUE,                 -- dùng cho manager/admin
    full_name   text NOT NULL,
    password    text,                        -- scrypt hash; NULL với guest (đăng nhập bằng token)
    role        text NOT NULL DEFAULT 'guest' CHECK (role IN ('guest','manager','admin')),
    login_token text UNIQUE,                 -- token cho link/QR cá nhân (guest)
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pbh_users_login_token ON pbh_users(login_token);

DROP TRIGGER IF EXISTS tr_pbh_users_update ON pbh_users;
CREATE TRIGGER tr_pbh_users_update
BEFORE UPDATE ON pbh_users
FOR EACH ROW EXECUTE FUNCTION pbh_update_timestamp();
