-- Active: Supabase SQL Editor
-- Migration 007: phiếu 1 số áp cho NHIỀU máy cùng model (kèm phụ lục danh sách serial).
-- App vẫn chạy khi chưa migrate (so_may mặc định 1; API bỏ qua nếu thiếu cột/bảng).

-- Số máy trên 1 phiếu (1 = phiếu thường; N = phiếu kèm danh sách serial)
ALTER TABLE pbh_phieu_bao_hanh
    ADD COLUMN IF NOT EXISTS so_may int NOT NULL DEFAULT 1;

-- Danh sách serial đính kèm 1 phiếu
CREATE TABLE IF NOT EXISTS pbh_phieu_serial (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phieu_id   bigint NOT NULL REFERENCES pbh_phieu_bao_hanh(id) ON DELETE CASCADE,
    serial     text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pbh_phieu_serial_phieu ON pbh_phieu_serial(phieu_id);
CREATE INDEX IF NOT EXISTS idx_pbh_phieu_serial_serial ON pbh_phieu_serial(serial);
