-- Active: Supabase SQL Editor

-- 1. Enable pg_trgm extension if not already enabled (useful for fuzzy search)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Function to remove Vietnamese accents/diacritics and convert to lowercase for fuzzy matching
CREATE OR REPLACE FUNCTION pbh_tieng_viet_khong_dau(str text)
RETURNS text AS $$
DECLARE
    result text;
BEGIN
    IF str IS NULL THEN
        RETURN '';
    END IF;

    result := lower(str);

    -- Replace accents
    result := regexp_replace(result, '[áàảãạăắằẳẵặâấầẩẫậ]', 'a', 'g');
    result := regexp_replace(result, '[éèẻẽẹêếềểễệ]', 'e', 'g');
    result := regexp_replace(result, '[íìỉĩị]', 'i', 'g');
    result := regexp_replace(result, '[óòỏõọôốồổỗộơớờởỡợ]', 'o', 'g');
    result := regexp_replace(result, '[úùủũụưứừửữự]', 'u', 'g');
    result := regexp_replace(result, '[ýỳỷỹỵ]', 'y', 'g');
    result := regexp_replace(result, '[đ]', 'd', 'g');

    -- Keep alphanumeric characters and spaces only, clean double spaces
    result := regexp_replace(result, '[^a-z0-9 ]', '', 'g');
    result := regexp_replace(result, '\s+', ' ', 'g');

    RETURN trim(result);
END;
$$ LANGUAGE plpgsql IMMUTABLE STRICT;

-- 3. Create Sequence for Ticket Number starting from 4279
CREATE SEQUENCE IF NOT EXISTS pbh_so_phieu_seq START WITH 4279;

-- 4. Bảng danh mục model máy và thông số cấu hình mặc định
CREATE TABLE IF NOT EXISTS pbh_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name text UNIQUE NOT NULL,
    loai_san_pham text NOT NULL DEFAULT 'Máy photocopy',
    hang_sx text NOT NULL,
    cau_hinh text NOT NULL DEFAULT 'Copy-In-Quét',
    so_ban_chup_mac_dinh integer NOT NULL DEFAULT 100000,
    so_thang_mac_dinh integer NOT NULL DEFAULT 12,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Trigger to update updated_at on pbh_models
CREATE OR REPLACE FUNCTION pbh_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_pbh_models_update
BEFORE UPDATE ON pbh_models
FOR EACH ROW EXECUTE FUNCTION pbh_update_timestamp();

-- 5. Bảng lưu trữ khách hàng (cho mục đích gợi ý & tham chiếu)
CREATE TABLE IF NOT EXISTS pbh_khach_hang (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_khach_hang text NOT NULL,
    ten_chuan_hoa text NOT NULL,
    dia_chi text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TRIGGER tr_pbh_khach_hang_update
BEFORE UPDATE ON pbh_khach_hang
FOR EACH ROW EXECUTE FUNCTION pbh_update_timestamp();

-- Index for fast fuzzy match search on normalized name
CREATE INDEX IF NOT EXISTS idx_pbh_khach_hang_ten_chuan_hoa ON pbh_khach_hang USING gin (ten_chuan_hoa gin_trgm_ops);

-- 6. Bảng phiếu bảo hành chi tiết
CREATE TABLE IF NOT EXISTS pbh_phieu_bao_hanh (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_phieu integer UNIQUE NOT NULL DEFAULT nextval('pbh_so_phieu_seq'),
    ngay_mua date NOT NULL DEFAULT current_date,
    khach_hang_id bigint REFERENCES pbh_khach_hang(id) ON DELETE SET NULL,
    ten_khach_hang text NOT NULL,
    dia_chi text NOT NULL,
    model_name text NOT NULL,
    loai_san_pham text NOT NULL,
    hang_sx text NOT NULL,
    cau_hinh text NOT NULL,
    serial text,
    dia_diem_bao_hanh text NOT NULL DEFAULT 'Tại khách hàng', -- 'Tại khách hàng' | 'Tại trung tâm'
    so_ban_chup integer NOT NULL,
    so_thang integer NOT NULL,
    trang_thai text NOT NULL DEFAULT 'cho_in', -- 'cho_in' | 'da_in' | 'huy'
    ma_tra_cuu text UNIQUE NOT NULL, -- UUID hoặc random code cho QR code
    nguoi_tao_id uuid, -- ID của user tạo từ auth.users (nếu có)
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TRIGGER tr_pbh_phieu_bao_hanh_update
BEFORE UPDATE ON pbh_phieu_bao_hanh
FOR EACH ROW EXECUTE FUNCTION pbh_update_timestamp();

-- Index for searching coupons
CREATE INDEX IF NOT EXISTS idx_pbh_phieu_bao_hanh_so_phieu ON pbh_phieu_bao_hanh(so_phieu);
CREATE INDEX IF NOT EXISTS idx_pbh_phieu_bao_hanh_serial ON pbh_phieu_bao_hanh(serial);
CREATE INDEX IF NOT EXISTS idx_pbh_phieu_bao_hanh_ma_tra_cuu ON pbh_phieu_bao_hanh(ma_tra_cuu);

-- Seed some default models if empty
INSERT INTO pbh_models (model_name, loai_san_pham, hang_sx, cau_hinh, so_ban_chup_mac_dinh, so_thang_mac_dinh)
VALUES
('Apeos 3561', 'Máy photocopy', 'Fujifilm', 'Copy-In-Quét', 100000, 12),
('bizhub 205i', 'Máy photocopy', 'Konica Minolta', 'Copy-In-Quét', 50000, 12),
('Ecosys M4132dn', 'Máy photocopy', 'Kyocera', 'Copy-In-Quét', 100000, 12),
('Apeos C2561', 'Máy photocopy', 'Fujifilm', 'Copy-In-Quét màu', 60000, 12),
('bizhub 651i', 'Máy photocopy', 'Konica Minolta', 'Copy-In-Quét', 500000, 12)
ON CONFLICT (model_name) DO NOTHING;
